### ISSUE TITLE
[Feature Request ] Support Mustache Tag Inheritance

### ISSUE THREAD

**Issue by soasme** [soasme/nim-mustache#13]
See https://github.com/mustache/spec/blob/master/specs/~inheritance.yml

**Comment by soasme** [comment]
Released in v0.4.1.

**Comment by pietroppeter** [comment]
I will have to update the specs document, then! 😄

**Comment by pietroppeter** [comment]
updated: https://pietroppeter.github.io/nblog/drafts/mustache_specs.html
