### ISSUE TITLE
Explicitly specify partial loaders

### ISSUE THREAD

**Issue by soasme** [soasme/nim-mustache#6]
*Issue*
I want to have different types of loaders, and am able to organize the order of these loaders.
Each loader provides a way to resolve templates.

*Example*

```
ctx = newContext()
ctx.searchDir("./")
ctx.searchTable(table)
```

Or in another order

```
ctx = newContext()
ctx.searchTable(table1)
ctx.searchDir("./")
ctx.searchTable(table2)
```

**Comment by soasme** [comment]
Feature implemented, see changelog v0.3.0.

**Comment by pietroppeter** [comment]
great, thanks, will use it very soon in my own [nimib](https://github.com/pietroppeter/nimib) (which also uses your other great library for markdown)! I also appreciate the fact that the default order created by `newContext` is first searchDirs and then in memory partials!

**Comment by pietroppeter** [comment]
I added a small note to the code [here](https://github.com/soasme/nim-mustache/commit/55516d12fc646c1a2cdad3ea6c9e7f734f4873ad#r44726377)
