### ISSUE TITLE
Access array element with index

### ISSUE THREAD

**Issue by benob** [soasme/nim-mustache#7]
Accessing an array element with its index seems to be unsupported.
```
import mustache
  
var c = newContext()
c["a"] = @[1, 2, 3]

echo "{{a.1}}".render(c)
```
It should output "2"

(for reference https://github.com/janl/mustache.js/issues/158)

Also, "{{a}}" outputs "@[]" which does seem the right thing (I don't know if it is expected by the specification).

**Comment by soasme** [comment]
@benob Thanks for reporting the issue. 

The feature has been among the new release in v0.3.2.

Below is the example:

```
import mustache

when isMainModule:
  var c = newContext()
  c["a"] = @[1, 2, 3]
  echo "{{#a}}{{.}}{{/a}}".render(c)
  echo "{{a.1}}".render(c)
  echo "{{a}}".render(c)
```

```
123
2
[1,2,3]
```

Appreciate any feedbacks!

**Comment by benob** [comment]
Turns out I was using 0.2.2. The new version works great, thanks.
