### ISSUE TITLE
unexpected whitespace when using lambda in a section

### ISSUE THREAD

**Issue by pietroppeter** [soasme/nim-mustache#8]
I was reproducing [mustache man (5)](https://pietroppeter.github.io/nimib/mostaccio.html)
with [nimib](https://pietroppeter.github.io/nimib/) (see [resulting document](https://pietroppeter.github.io/nimib/mostaccio.html))
and I ran into this unexpected behaviour when using lambdas in a section:

```nim
import mustache

var tmpl = """
{{#wrapped}}
  {{name}} is awesome.
{{/wrapped}}"""
var context = newContext()
context["name"] = "Willy"
context["wrapped"] = proc(s: string, c: Context): string = "<b>" & s.render(c) & "</b>"
echo tmpl.render(context)
#[
  output:
<b>  Willy is awesome.
</b>  
  expected:
<b>Willy is awesome.</b>
]#
```

There is not test similar to this in [the specs](https://github.com/mustache/spec/blob/master/specs/~lambdas.yml) so probably it is not necessarily something that has a definite behaviour.

While looking in the specs I saw that there is a new version of specs with a new optional feature: inheritance, see this PR: https://github.com/mustache/spec/pull/125

Also, I see that there is a ongoing PR to update musache man (5) to the most recent specs: https://github.com/mustache/mustache/pull/266

Looking at this PR I found out that the lambda functionality has a simplified version: https://github.com/mustache/mustache/pull/266

I think I will try to download the latest version of specs and produce an automatically generated nimib document running all tests and showing outputs.

Maybe we could add the above document ([mustache man (5) for nim-mustache](https://pietroppeter.github.io/nimib/mostaccio.html)) and the one with the specs (when I do it) as link in the readme (in the references sections?)?

**Comment by soasme** [comment]
The lambda functionality purposely let users decide how to deal with indent & trailing inside the wrapped block. To produce an expected output, you can strip the input string before rendering:

```
context["wrapped"] = proc(s: string, c: Context): string = "<b>" & s. strip.render(c) & "</b>"
```

**Comment by pietroppeter** [comment]
ok, makes sense, I updated accordingly my document
